name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ['3.11', '3.12', '3.13']
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          py -3 -m pip install --upgrade pip
          if (Test-Path requirements.txt) { py -3 -m pip install -r requirements.txt } else { py -3 -m pip install pytest }
          # install docx generator dependency
          py -3 -m pip install python-docx
        shell: powershell
      - name: Run tests
        run: py -3 -m pytest -q
        shell: powershell
      - name: Generate developer manual
        run: py -3 tools/generate_code_manual.py
        shell: powershell
      - name: Upload reports artifact
        uses: actions/upload-artifact@v4
        with:
          name: developer-manual
          path: reports/*.docx
